before_install:
  - gem install cocoapods -v '0.35.0'
osx_image: xcode6.4
language: objective-c
xcode_workspace: ./Example/EditorDemo.xcworkspace
xcode_scheme: EditorDemo
xcode_sdk: iphonesimulator8.4
sudo: false
